### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by Sid127** [TeamPiped/Piped#3158]
### Describe the feature

Forgot Password button on login screen

### Why would this be useful to add?

Recover accounts where the password was mistyped in mysterious ways.

### Additional context

Since we don't use emails or phone numbers for accounts, this would require another method of authentication, like 2FA keys.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
We've already addressed this problem in two different ways:
1. Users need to confirm their password - if a user manages to mistype the password twice it's their fault
2. There's a WIP work on logging in with other services using OIDC, which will make it obsolete to require an extra password for Piped and let the OIDC provider handle the authentication

**Comment by maknouichi-sensei** [comment]
did you ever recover the account? i have the same issue, i know my username but forgot my password. there should be a two step vertification where it asks you what your favorite color is or something only you would know, if you forgot password.
